spring:
  datasource:
    username: main_owner
    password: Hka9pA2Nozeu
    url: jdbc:postgresql://ep-super-smoke-a2zzrmgn.eu-central-1.aws.neon.tech/main?sslmode=require
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

json:
  placeholder:
    path: https://jsonplaceholder.typicode.com/