spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:/Users/pavel/IdeaProjects/JavaVkTest/VkRestApi/src/main/resources/data
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: true
    properties:
      hibernate:
        format_sql: true
